config/routes.rb
Photoportfolio::Application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registration" } 

  root to: "genres#index"

  match "/about",       to: "static_pages#about"
  match "/contact",     to: "static_pages#contact"
  match "/help",        to: "static_pages#help"

  resources :genres, except: [:show] do 
    resources :albums, except: [:show] 
  end
    
  resources :albums, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
     resources :paintings, except: [:show]
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :genre_id 

  belongs_to :genre
  has_many :paintings, dependent: :destroy

  validates :name, :genre_id, presence: true
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name
  
  has_many :albums, dependent: :destroy

  validates :name, presence: true
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :image, :name, :album_id

  belongs_to :album

  validates :name, :album_id,  presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :token_authenticatable, :confirmable, :lockable, :timeoutable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_filter :authenticate_user!, except: [:index]
  before_filter :get_genre

  def get_genre
     @genre = Genre.find(params[:genre_id])
  end

  def index
     @albums = @genre.albums
  end


  def new 
    @album = Album.new(genre_id: params[:genre_id])
  end

  def create
    @album = @genre.albums.new(params[:album])
    if @album.save
      flash[:notice] = "Successfuly created album."
      redirect_to genre_albums_url
    else
      render action: 'new'
    end
  end

  def edit
    @album = @genre.albums.find(params[:id])
  end

  def update
    @album = @genre.albums.find(params[:id])
    if @album.update_attributes(params[:album])
      flash[:notice] = "Successfuly updated album."
      redirect_to genre_albums_url
    else
      render action: 'edit'
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    flash[:notice] = "Successfuly destroyed album."
    redirect_to genre_albums_url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_filter :authenticate_user!, except: [:index]

  def index
     @genres = Genre.find(:all)
  end

  def new
     @genre = Genre.new
  end

  def create
     @genre = Genre.new(params[:genre])
     if @genre.save
       flash[:notice] = "Successfuly created genre."
       redirect_to root_url
     else
       render action: 'new'
     end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update_attributes(params[:genre])
      flash[:notice] = "Successfuly updated genre."
      redirect_to root_url
    else
      render action: 'edit'
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    flash[:notice] = "Successfuly destroyed genre."
    redirect_to root_url
  end

end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  before_filter :authenticate_user!, except: [:index]
  before_filter :get_album

  def get_album
    @album = Album.find(params[:album_id])
  end

  def index
     @paintings = @album.paintings
  end

  def show
     @painting = @album.paintings.find(params[:id])
  end

  def new
    @painting = Painting.new(album_id: params[:album_id])
  end

  def create
    @painting = @album.paintings.new(params[:painting])
    if @painting.save
      flash[:notise] = "Successfuly created painting."
      redirect_to album_paintings_url
    else
      render action: 'new'
    end
  end

  def edit
    @painting = @album.paintings.find(params[:id])
  end

  def update
    @painting = @album.paintings.find(params[:id])
    if @painting.update_attributes(params[:painting])
      flash[:notice] = "Successfuly updated painting."
      redirect_to album_paintings_url
    else
      render action: 'edit'
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    flash[:notice] = "Successfuly destroyed painting."
    redirect_to album_paintings_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def contact
  end

  def help
  end
end

app/controllers/users/registration_controller.rb
class Users::RegistrationController < Devise::RegistrationsController

  def create
    if verify_recaptcha(timeout: 10)
      super
    else
      build_resource
      clean_up_passwords(resource)
      flash.now[:alert] = "There was an error with the recaptcha code below. Please re-enter the code."      
      flash.delete :recaptcha_error
      render :new
    end
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper

  def title_album_image(album)
    if  album.paintings.first
       album.paintings.first.image_url(:thumb)
    else
      "No images"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title 
  
  def full_title(page_title)
    base_title = "Photoportfolio"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/genres_helper.rb
module GenresHelper

  def title_genre_image(genre)
    if genre.albums.first
     if genre.albums.first.paintings.first
      genre.albums.first.paintings.first.image_url(:thumb) 
     else
       "No images in albums"
     end
    else
      "No albums"
    end
  end
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/albums/_fields.html.erb
  <%= f.hidden_field :genre_id %>
<p>
  <% f.label :name %>
  <%= f.text_field :name %>
</p>

app/views/albums/edit.html.erb
<% provide(:title, 'Edit album') %>
<h1>Edit album</h1>

<div class="row">
  <div class="span2">
    <%= form_for([@genre, @album]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= render 'fields', f: f %>

      <%= f.submit "Save", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/albums/index.html.erb
<% provide(:title, @genre.name) %>

<% if user_signed_in? %>
  <div class="row-fluid">
   <div class="span3 well center">
     <%= link_to "Add album", new_genre_album_url(@genre) %><br />
     <%= link_to "Revert back", root_url %>
   </div>
   <div class="span9 well center" >
     <h3>
       <%= "Genre " + @genre.name %>
     </h3>
     <% @albums.each do |album| %>
      <p>
       <ul>
         <li class="span3">
           <div class="thumbnail center">
             <%= link_to (image_tag title_album_image(album)), album_paintings_url(album) %> 
             <h4>
               <%= link_to "Album " + album.name, album_paintings_url(album) %> - <%= album.paintings.count %> images
             </h4>
             <h5>
               <%= link_to "Edit", edit_genre_album_url(@genre, album) %>
               <%= link_to "Delete", [@genre, album], method: :delete, data: { confirm: "You sure?" } %>
             </h5>
           </div>
         </li>
       </ul>
      </p>
     <% end %>
   </div>
  </div>
<% else %>
  <div class="row-fluid">
   <div class="span3 well">
        <%= link_to "Revert back", root_url %>
   </div>
   <div class="span9 well center" >
     <h3>
       <%= "Genre " +  @genre.name %>
     </h3>
     <% @albums.each do |album| %>
      <p>
       <ul>
         <li class="span3">
           <div class="thumbnail center">
             <%= link_to (image_tag title_album_image(album)), album_paintings_url(album) %> 
             <h4>
               <%= link_to "Album " + album.name, album_paintings_url(album) %> - <%= album.paintings.count %> images
             </h4>
           </div>
         </li>
       </ul>
      </p>
     <% end %>
   </div>
  </div>
<% end %>

app/views/albums/new.html.erb
<% provide(:title, 'Add album') %>
<h1>Add album</h1>

<div class="row">
  <div class="span2">
    <%= form_for([@genre, @album]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= render 'fields', f: f %>

      <%= f.submit "Add", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/genres/_fields.html.erb
<p>
  <% f.label :name %>
  <%= f.text_field :name %>
</p>

app/views/genres/edit.html.erb
<% provide(:title, 'Edit genre') %>
<h1>Edit genre</h1>

<div class="row">
  <div class="span2">
    <%= form_for(@genre) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= render 'fields', f: f %>

      <%= f.submit "Save", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/genres/index.html.erb
<% provide(:title, "Home page") %>

<% if user_signed_in? %>
  <div class="row-fluid">
    <div class="span3 well center">
      <%= link_to "Add genre", new_genre_url %>
    </div>
    <div class="span9 well center">
     <h3>
       Genres
     </h3>
     <% @genres.each do |genre| %>
     <p>
       <ul>
         <li class="span3">
           <div class="thumbnail center">
               <%= link_to (image_tag title_genre_image(genre)), genre_albums_url(genre)  %> 
               <h4>
                 <%= link_to genre.name, genre_albums_url(genre) %> - <%= genre.albums.count %> albums
               </h4>
               <h5>
                 <%= link_to "Edit", edit_genre_url(genre) %>
                 <%= link_to "Delete", genre, method: :delete, data: { confirm: "You sure?" }%>
             </h5>
           </div>
         </li>
       </ul>
     </p>
     <% end %>
    </div>
  </div>
<% else %>
  <div class="row-fluid">
    <div class="span12 hero-unit center">
     <h3>
       Genres
     </h3>
     <% @genres.each do |genre| %>
     <p>
       <ul>
         <li class="span3">
           <div class="thumbnail center">
               <%= link_to (image_tag title_genre_image(genre)), genre_albums_url(genre)  %> 
               <h4>
                 <%= link_to genre.name, genre_albums_url(genre) %> - <%= genre.albums.count %> albums
               </h4>
           </div>
         </li>
       </ul>
     </p>
     <% end %>
    </div>
  </div>
<% end %>

app/views/genres/new.html.erb
<% provide(:title, 'Add Genre') %>
<h1>Add Genre</h1>

<div class="row">
  <div class="span2">
    <%= form_for(@genre) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= render 'fields', f: f %>

      <%= f.submit "Add", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/_debug.html.erb
<div>
  <% if Rails.env.development? %>      
    <%= debug(params) %>               
    <div class="breadcrumb" >
      <%= render 'layouts/options' %>  
    </div>
  <% end %>                            
</div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <div class="navbar-inner">
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header navbar navbar-fixed-top">
<div class="navbar-inner">
  <div class="container-fluid">
    <nav>
      <ul class="logo nav pull-left">
        <li><%= link_to "Photoportfolio", root_url %></li> 
      </ul>
    </nav>
    <nav>
      <ul class="nav pull-left">
        <li><%= link_to "About", about_url %></li>
        <li><%= link_to "Contact", contact_url %></li>
        <li><%= link_to "Help", help_url %></li>
      </ul>
    </nav>
    <nav>
      <ul class="nav pull-right">
        <li>
          <form class="navbar-search">                                   
            <input type="text" class="search-query" placeholder="Search">
          </form>                                                        
        </li>
        <% if user_signed_in? %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", "#" %></li>
              <li><%= link_to "Settings", edit_user_registration_url %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_url, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_url %></li>
          <li><%= link_to "Sign in", new_user_session_url %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_options.html.erb
<div>
  Method: <%= request.method %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div class="container">
    <div>
      <%= render 'layouts/header' %>
    </div>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
    <div>
      <%= render 'layouts/debug' %>
      <%= render 'layouts/footer' %>
    </div>
</div>
</body>
</html>

app/views/paintings/_fields.html.erb
  <%= f.hidden_field :album_id %>
<p>                              
  <%= f.label :name %>            
  <%= f.text_field :name %>      
</p>                             
<p>
  <%= f.file_field :image %>
</p>

app/views/paintings/edit.html.erb
<% provide(:title, 'Edit painting') %>
<h1>Edit painting</h1>

<div class="row">
  <div class="span2">
    <%= form_for([@album, @painting]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= render 'fields', f: f %>

      <%= f.submit "Save", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/paintings/index.html.erb
<% provide(:title, @album.name) %>

<% if user_signed_in? %>

  <div class="row-fluid">
    <div class="span3 well center">
      <%= link_to "Add image", new_album_painting_url(@album) %><br />
      <%= link_to "Revert back", genre_albums_url(@album.genre) %>
    </div>
    <div class="span9 well center" >
      <h3>
        <%= "Album " + @album.name %>
      </h3>
      <% @paintings.each do |painting| %>
      <p>
        <ul>
          <li class="span3">
            <div class="thumbnail center">
                <%= link_to (image_tag painting.image_url(:thumb)), painting.image_url, data: { colorbox: true }, title: painting.name if painting.image? %> 
              <h4>
                <%= painting.name %> 
              </h4>
              <h5>
                <%= link_to "Edit", edit_album_painting_url(@album, painting) %>
                <%= link_to "Delete", [@album, painting],  method: :delete, data: { confirm: "You sure?" } %>
              </h5>
            </div>
          </li>
        </ul>
      </p>
    <% end %>
   </div>
  </div>

<% else %>

  <div class="row-fluid">
    <div class="span3 well">
      <%= link_to "Revert back", genre_albums_url(@album.genre) %>
    </div>
    <div class="span9 well center" >
      <h3>
        <%= "Album " + @album.name %>
      </h3>
      <% @paintings.each do |painting| %>
      <p>
        <ul>
          <li class="span3">
            <div class="thumbnail center">
                <%= link_to (image_tag painting.image_url(:thumb)), painting.image_url, data: { colorbox: true }, title: painting.name if painting.image? %> 
              <h4>
                <%= painting.name %> 
              </h4>
            </div>
          </li>
        </ul>
      </p>
    <% end %>
   </div>
  </div>

<% end %>

app/views/paintings/new.html.erb
<% provide(:title, 'Add painting') %>
<h1>Add painting</h1>

<div class="row">
  <div class="span2">
    <%= form_for([@album, @painting]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= render 'fields', f: f %>

      <%= f.submit "Add", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div "error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About As') %>

<div class="row-fluid">         
  <div class="span5 well"> 
    <p>Side 1</p>               
  </div>                        
  <div class="span7 well"> 
    <p>Side 2</p>               
  </div>                        
</div>                            

app/views/static_pages/contact.html.erb
<% provide(:title, "Ours contacts") %>

<div class="row-fluid">         
  <div class="span5 well"> 
    <p>Side 1</p>               
  </div>                        
  <div class="span7 well"> 
    <p>Side 2</p>               
  </div>                        
</div>                            

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<div class="row-fluid">         
  <div class="span5 well"> 
    <p>Side 1</p>               
  </div>                        
  <div class="span7 well"> 
    <p>Side 2</p>               
  </div>                        
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>